version: "3.9"

services: 
    api:
        build: .
        container_name: api-service
        ports: 
            - "8000:80"
        command: uvicorn api.entry:app --host 0.0.0.0 --port 80 --reload
        volumes: 
            - ./api:/app/api
        environment: 
            - APP_ENV=development
            - DEBUG=1