version: "3.9"

services: 
    api:
        build: .
        container_name: api-service
        ports: 
            - "80:8000"
        command: uvicorn api.entry:app --host 0.0.0.0 --port 8000 --reload
        volumes: 
            - ./api:/app/api