version: "3.9"

services: 
    api:
        build: .
        container_name: api-service
        ports: 
            - "8000:80"
        command: uvicorn api.entry:app --host 0.0.0.0 --port 80 --reload
        volumes: 
            - ./api:/api
        environment: 
            - APP_ENV=development
            - DEBUG=1
        depends_on:
            - database

    database:
        image: postgres:13-alpine
        container_name: database-service
        restart: always
        ports: 
            - "5432:5432"
        environment: 
            - POSTGRES_DB=tododb
            - POSTGRES_USER=youness
            - POSTGRES_PASSWORD=youness